# Generated by Django 5.0.2 on 2025-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
